spring.datasource.url=jdbc:mysql://localhost:3306/dsr_portal
spring.datasource.username=root
spring.datasource.password=@gana2908

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080